version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "profile-service"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-7idfnjoy8ob3"
s3_prefix = "profile-service"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
